# Generated by Django 5.2.4 on 2025-07-30 19:38

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Candidat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('prenom', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('date_candidature', models.DateField()),
                ('cv', models.FileField(upload_to='cv/')),
                ('lettre_motivation', models.FileField(upload_to='lettres/')),
                ('statut_candidature', models.CharField(choices=[('REÇUE', 'Reçue'), ('EN_EXAMEN', 'En examen'), ('QUALIFIÉE', 'Qualifiée'), ('ENTRETIEN', 'Entretien'), ('ACCEPTÉE', 'Acceptée'), ('REFUSÉE', 'Refusée')], max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Personne',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('prenom', models.CharField(max_length=100)),
                ('date_naissance', models.DateField()),
                ('lieu_naissance', models.CharField(max_length=100)),
                ('nni', models.CharField(max_length=10, unique=True)),
                ('nationalite', models.CharField(max_length=100)),
                ('genre', models.CharField(choices=[('MASCULIN', 'Masculin'), ('FEMININ', 'Féminin')], max_length=10)),
                ('situation_familiale', models.CharField(max_length=50)),
                ('adresse', models.TextField()),
                ('nom_pere', models.CharField(max_length=100)),
                ('dernier_diplome', models.CharField(max_length=200)),
                ('pays_obtention_diplome', models.CharField(max_length=100)),
                ('annee_obtention_diplome', models.IntegerField()),
                ('specialite_formation', models.CharField(max_length=200)),
                ('fonction', models.CharField(max_length=100)),
                ('manager', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='equipe', to='myapp.personne')),
            ],
        ),
        migrations.CreateModel(
            name='StatutAbsence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('libelle', models.CharField(choices=[('EN_ATTENTE', 'En attente'), ('APPROUVÉ', 'Approuvé'), ('REFUSÉ', 'Refusé'), ('ANNULÉ', 'Annulé')], max_length=15, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='StatutCandidature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('libelle', models.CharField(choices=[('REÇUE', 'Reçue'), ('EN_EXAMEN', 'En examen'), ('QUALIFIÉE', 'Qualifiée'), ('ENTRETIEN', 'Entretien'), ('ACCEPTÉE', 'Acceptée'), ('REFUSÉE', 'Refusée')], max_length=20, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='StatutOffre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('libelle', models.CharField(choices=[('REÇUE', 'Reçue'), ('EN_EXAMEN', 'En examen'), ('QUALIFIÉE', 'Qualifiée'), ('ENTRETIEN', 'Entretien'), ('ACCEPTÉE', 'Acceptée'), ('REFUSÉE', 'Refusée')], max_length=20, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='StatutPaiement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('libelle', models.CharField(choices=[('EN_COURS', 'En cours'), ('PAYÉ', 'Payé'), ('SUSPENDU', 'Suspendu'), ('ANNULÉ', 'Annulé')], max_length=15, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='TypeAbsence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('libelle', models.CharField(choices=[('CONGÉ_ANNUEL', 'Congé annuel'), ('CONGÉ_MALADIE', 'Congé maladie'), ('CONGÉ_MATERNITÉ', 'Congé maternité'), ('DÉTACHEMENT', 'Détachement'), ('DISPONIBILITÉ', 'Disponibilité'), ('ANNÉE_SABBATIQUE', 'Année sabbatique')], max_length=20, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='TypeContrat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('libelle', models.CharField(choices=[('CDD', 'CDD'), ('CDI', 'CDI')], max_length=10, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='TypeDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('libelle', models.CharField(choices=[('CONTRAT', 'Contrat'), ('COTE_NOMINATION', 'Cote de nomination'), ('DIPLÔME', 'Diplôme'), ('CERTIFICAT', 'Certificat'), ('ÉVALUATION', 'Évaluation')], max_length=20, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='TypeEmploye',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('libelle', models.CharField(choices=[('ENSEIGNANT', 'Enseignant'), ('PERSONNEL_PAT', 'Personnel PAT'), ('CONTRACTUEL', 'Contractuel')], max_length=20, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='TypeStructure',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('libelle', models.CharField(choices=[('ENSEIGNEMENT', 'Enseignement'), ('ADMINISTRATION', 'Administration'), ('RECHERCHE', 'Recherche'), ('TECHNIQUE', 'Technique')], max_length=20, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Contractuel',
            fields=[
                ('personne', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='myapp.personne')),
                ('type_contrat', models.CharField(choices=[('CDD', 'CDD'), ('CDI', 'CDI')], max_length=10)),
                ('duree_contrat', models.CharField(max_length=100)),
                ('date_debut_contrat', models.DateField()),
                ('date_fin_contrat', models.DateField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Enseignant',
            fields=[
                ('personne', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='myapp.personne')),
                ('corps', models.CharField(max_length=100)),
                ('grade', models.CharField(max_length=100)),
                ('echelon', models.CharField(max_length=50)),
                ('indice', models.IntegerField()),
                ('date_entree_service_publique', models.DateField()),
                ('date_entree_enseignement_superieur', models.DateField()),
                ('date_fin_service_obligatoire', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='PersonnelPAT',
            fields=[
                ('personne', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='myapp.personne')),
                ('grade', models.CharField(max_length=100)),
                ('nbi_mac', models.IntegerField()),
                ('indice', models.IntegerField()),
                ('anciennete_echelon', models.CharField(max_length=50)),
                ('date_changement', models.DateField()),
                ('anciennete_grade', models.CharField(max_length=50)),
                ('date_nomination', models.DateField()),
                ('date_prise_service', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Absence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_absence', models.CharField(choices=[('CONGÉ_ANNUEL', 'Congé annuel'), ('CONGÉ_MALADIE', 'Congé maladie'), ('CONGÉ_MATERNITÉ', 'Congé maternité'), ('DÉTACHEMENT', 'Détachement'), ('DISPONIBILITÉ', 'Disponibilité'), ('ANNÉE_SABBATIQUE', 'Année sabbatique')], max_length=20)),
                ('date_debut', models.DateField()),
                ('date_fin', models.DateField()),
                ('statut', models.CharField(choices=[('EN_ATTENTE', 'En attente'), ('APPROUVÉ', 'Approuvé'), ('REFUSÉ', 'Refusé'), ('ANNULÉ', 'Annulé')], max_length=15)),
                ('document_justificatif', models.FileField(blank=True, null=True, upload_to='justificatifs/')),
                ('date_demande_absence', models.DateField()),
                ('motif_refus', models.TextField(blank=True)),
                ('personne', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='absences', to='myapp.personne')),
            ],
        ),
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=200)),
                ('type_document', models.CharField(choices=[('CONTRAT', 'Contrat'), ('COTE_NOMINATION', 'Cote de nomination'), ('DIPLÔME', 'Diplôme'), ('CERTIFICAT', 'Certificat'), ('ÉVALUATION', 'Évaluation')], max_length=20)),
                ('chemin_fichier', models.FileField(upload_to='documents/')),
                ('taille_fichier', models.BigIntegerField()),
                ('date_upload', models.DateTimeField(auto_now_add=True)),
                ('proprietaire', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='myapp.personne')),
            ],
        ),
        migrations.CreateModel(
            name='Structure',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=255)),
                ('type_structure', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('parent_structure', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sous_structures', to='myapp.structure')),
                ('responsable', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='structures_dirigees', to='myapp.personne')),
            ],
        ),
        migrations.CreateModel(
            name='Recrutement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('prenom', models.CharField(max_length=100)),
                ('type_employe', models.CharField(choices=[('ENSEIGNANT', 'Enseignant'), ('PERSONNEL_PAT', 'Personnel PAT'), ('CONTRACTUEL', 'Contractuel')], max_length=20)),
                ('type_employe_specifique', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('requis_post', models.TextField()),
                ('date_limite', models.DateField()),
                ('date_entree', models.DateField()),
                ('statut_offre', models.CharField(max_length=50)),
                ('structure_recruteur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.structure')),
            ],
        ),
        migrations.CreateModel(
            name='Detachement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('acte_detachement', models.FileField(upload_to='detachements/')),
                ('date_debut_detachement', models.DateField()),
                ('date_fin_detachement', models.DateField()),
                ('motif_detachement', models.TextField()),
                ('personne', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detachements', to='myapp.personne')),
                ('structure_detachement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detachements_entrants', to='myapp.structure')),
                ('structure_origine', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detachements_sortants', to='myapp.structure')),
            ],
        ),
        migrations.CreateModel(
            name='Paie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('salaire_net', models.DecimalField(decimal_places=2, max_digits=10)),
                ('salaire_brut', models.DecimalField(decimal_places=2, max_digits=10)),
                ('nb_enfants', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)])),
                ('deductions', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('date_paiement', models.DateField()),
                ('mois_annee', models.CharField(max_length=7)),
                ('statut_paiement', models.CharField(choices=[('EN_COURS', 'En cours'), ('PAYÉ', 'Payé'), ('SUSPENDU', 'Suspendu'), ('ANNULÉ', 'Annulé')], max_length=15)),
                ('personne', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='paies', to='myapp.personne')),
            ],
            options={
                'unique_together': {('personne', 'mois_annee')},
            },
        ),
    ]
