# Generated by Django 5.2.1 on 2025-12-12 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='absence',
            name='motif',
            field=models.TextField(blank=True, help_text="Raison de l'absence fournie par l'employé"),
        ),
    ]
