# Generated by Django 5.2.1 on 2025-12-13 14:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_absence_motif'),
    ]

    operations = [
        migrations.AddField(
            model_name='paie',
            name='compte_bancaire',
            field=models.CharField(blank=True, help_text='Numéro de compte bancaire', max_length=200),
        ),
        migrations.AddField(
            model_name='paie',
            name='echelon',
            field=models.CharField(blank=True, help_text='Échelon', max_length=10),
        ),
        migrations.AddField(
            model_name='paie',
            name='grade',
            field=models.CharField(blank=True, help_text="Grade de l'employé", max_length=200),
        ),
        migrations.AddField(
            model_name='paie',
            name='indice',
            field=models.CharField(blank=True, help_text='Indice', max_length=10),
        ),
        migrations.AddField(
            model_name='paie',
            name='mode_reglement',
            field=models.CharField(blank=True, help_text='Mode de règlement (ex: Code 340)', max_length=100),
        ),
        migrations.AddField(
            model_name='paie',
            name='montant_imposable_mensuel',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='paie',
            name='montant_imposable_progressif',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.CreateModel(
            name='ElementPaie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(help_text="Code de l'élément (ex: 210, 600)", max_length=10)),
                ('libelle', models.CharField(help_text="Libellé de l'élément", max_length=200)),
                ('type_element', models.CharField(choices=[('GAIN', 'Gain'), ('RETENUE', 'Retenue')], max_length=10)),
                ('taux', models.DecimalField(blank=True, decimal_places=2, help_text='Taux en pourcentage', max_digits=5, null=True)),
                ('montant', models.DecimalField(decimal_places=2, help_text='Montant', max_digits=10)),
                ('date_debut', models.DateField(blank=True, null=True)),
                ('date_fin', models.DateField(blank=True, null=True)),
                ('ordre', models.IntegerField(default=0, help_text="Ordre d'affichage")),
                ('paie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='elements', to='myapp.paie')),
            ],
            options={
                'ordering': ['ordre', 'code'],
            },
        ),
    ]
